### ISSUE TITLE
$msg don't get converted properly

### ISSUE THREAD

**Issue by mathiashelin** [Thijzer/ConverterCollection#6]
Almost every message (if not every message) gets converted to `{{ msg.Something }}`.

**Comment by Thijzer** [comment]
Hi @mathiashelin,

Could you give a good example? 
```
{input}, {output}, {expected output}
```

**Comment by mathiashelin** [comment]
{$msgBlogOneComment}, {{ msg.BlogOneComment }}, {{ 'msg.BlogOneComment'|trans }}
Same with errors, actions, actually. Only lbl's were mostly correct.

**Comment by Thijzer** [comment]
should be fixed now, also fixed the --file option
